
project_id = "pbpipqltnkhnchhjmkrr"

[functions.analyze-cv]
verify_jwt = false
import_map = "./import_map.json"

[[functions.analyze-cv.cors]]
origin = "*"
headers = ["*"]
methods = ["POST"]

[functions.edit-cv]
verify_jwt = false
import_map = "./import_map.json"

[[functions.edit-cv.cors]]
origin = "*"
headers = ["*"]
methods = ["POST"]
